spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000  # 30 segundos
      idle-timeout: 600000     # 10 minutos
      max-lifetime: 1800000    # 30 minutos
      validation-timeout: 5000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update  # Use update para não recriar tabelas a cada inicialização
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.springframework: DEBUG