version: '3.8'
services:
  db:
    image: postgres:15
    container_name: railway
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: railway
    ports:
      - "5433:5432"

  client:
    image: postgres:15
    depends_on:
      - db
    entrypoint: ["sleep", "infinity"] # para manter o container rodando interativamente
